### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by Kaarl0** [mego323/mr-prime#1]
On termux it cannot be seted up, i tried all programs after i runned install.sh but it doesn't work.

**Comment by Kaarl0** [comment]
> On termux it cannot be seted up, i tried all programs after i runned install.sh but it doesn't work.

Sorry, there is no issue, I'm just stupid.

**Comment by mego323** [comment]
hey man don't say that 
we all make mistakes it's life

**Comment by isaka-james** [comment]
now it's working, you should try it now @Kaarl0  , 
but in 10th May 2024, we'll have the whole updated and modern tool!
